[workspace]
members = [
    "trunk", "trunk-plugin", "trunk-derive",
    "examples/plugin", "examples/plugin/hello_world_plugin", "examples/seed", "examples/yew"
]

[profile.release]
lto = "fat"
codegen-units = 1
